### ISSUE TITLE
MergeProps in RouteDefinitions data result in Proxy error

### ISSUE THREAD

**Issue by TheFedaikin** [ryansolid/solid-app-router#6] opened 2021-03-03 09:02 UTC
### Good day, library maintainers!
I was playing around with this router (and solid in general) and wanted to say thank you for this awesome library, and ecosystem you are working on. This is a breath of fresh air and I am definitely looking forward to incorporate Solid into my work!

I looked into the source code for this router and found out how to use data object. But I found out that if you are using mergeProps in the **`data`** property in route definitions it's breaking with Proxy error, but if I just return new object (without mergeProps) it's working as intended. 

I am not sure it's a solid-app-router bug or bug in the main library, but I didn't encounter this before, while using solid without this router.

Error:
```'ownKeys' on proxy: trap result did not include 'Symbol(state-proxy)'```

### [Repro link](https://codesandbox.io/s/dazzling-babbage-euqkz?file=/src/main.tsx)

I might've misunderstood something with mergeProps so it might not be a bug at all.

**Comment by ryansolid** [comment] 2021-03-03 17:03
Interesting. This is likely a bug in the `mergeProps` helper. It looks like it is expecting different handling of internal symbols. Thanks for the reproduction this should be easier to track down the right solution.

**Comment by ryansolid** [comment] 2021-03-08 22:15
I am still looking at this. I do have a fix that works. But this whole thing makes me think I'm missing something important in my understanding so I'm taking my time to make sure I get this right before I release it.

**Comment by TheFedaikin** [comment] 2021-03-11 09:54
Thanks for the update! Looking forward to the next version!

**Comment by ryansolid** [comment] 2021-03-14 09:15
Ok fixed in solid v0.24.14

**Closed by ryansolid** 2021-03-14 09:15 UTC
Labels: bug
